### ISSUE TITLE
\texbf加粗宋体后字体变为黑体

### ISSUE THREAD

**Issue by JLee2022** [Markhng/whutmod#1]
**Describe the bug*
\textbf {... ...(宋体)}
texstudio输出结果为黑体，行间距变大，字体格式不统一

**Comment by huangyxi** [comment]
尚不能确定问题所在，我在[标准环境](../blob/master/demo.tex)下测试[demo.tex](../blob/master/demo.tex)的摘要、正文部分\textbf指令的输出均为黑体（正常情况）、行间距不变。
如果环境与代码不同，烦请按照[模板](./new?assignees=&labels=bug&template=bug_report.md&title=)提供测试环境信息以及最小工作示例(MWE)。

> **Minimum Working Example (MWE)**
A minimum example code that can reproduce the behavior.
The overall code should generally not exceed 10 lines.

**Comment by huangyxi** [comment]
如果没什么问题的话issue就关了。如果还有问题可以新开issue。

**Comment by JLee2022** [comment]
好的，多谢答复

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
